### ISSUE TITLE
http://www.yours.works/ gets blocked while https://calendar-mixer.herokuapp.com/ doesn't?

### ISSUE THREAD

**Issue by TheBlueness** [AndrewLester/CalendarMixer#2]
![Screen Shot 2020-03-25 at 4 13 37 PM](https://user-images.githubusercontent.com/12973114/77581566-4fc99100-6eb4-11ea-999c-d04c9f8ba3ab.png)

**Comment by AndrewLester** [comment]
Sticking with HTTPS here so yours.works is not a usable alternate anymore.
